# Generated by Django 4.2.2 on 2023-06-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_candidate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_recruiter',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], max_length=25, null=True),
        ),
    ]
