# Generated by Django 4.2.2 on 2023-07-07 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0004_application_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
