# Generated by Django 4.2.2 on 2023-06-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0005_remove_profile_is_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], default='', max_length=25),
        ),
    ]
