# Generated by Django 4.2.2 on 2023-07-07 15:56

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Job = apps.get_model("jobseekapp", "Job")
    for row in Job.objects.all():
        row.unique_identifier = uuid.uuid4()
        row.save(update_fields=["unique_identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0005_job_unique_identifier'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
