# Generated by Django 4.2.2 on 2023-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0006_profile_company_name_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='employee_count',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_loctype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter_firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter_lastname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
