# Generated by Django 4.2.2 on 2023-07-07 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0006_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
