# Generated by Django 4.2.2 on 2023-06-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0010_recruitergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitergroup',
            options={'verbose_name_plural': 'Recruiter Groups'},
        ),
    ]
