# Generated by Django 4.2.2 on 2023-06-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobseekapp', '0011_alter_recruitergroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitergroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruiter_group', serialize=False, to='auth.group'),
        ),
    ]
