# Generated by Django 4.2.2 on 2023-06-25 01:30
from django.db import migrations


def grant_insert_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    try:
        recruiter_group = Group.objects.get(name='RecruiterGroup')
        # Get the "add" permission for the relevant model
        permission = Permission.objects.get(content_type__app_label='jobseekapp', content_type__model='job', codename='add_job')

        # Grant the "add" permission to all users in the recruiter group
        recruiter_group.permissions.add(permission)

    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0012_alter_recruitergroup_group'),  # Replace with the actual previous migration name
    ]

    operations = [
        migrations.RunPython(grant_insert_permissions),
    ]
