# Generated by Django 4.2.2 on 2023-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0016_application_email_application_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_questions',
            field=models.BooleanField(default=False),
        ),
    ]
