# Generated by Django 4.2.2 on 2023-06-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0018_jobquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobquestion',
            old_name='options',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='jobquestion',
            old_name='text',
            new_name='question',
        ),
    ]
