# Generated by Django 4.2.2 on 2023-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0019_rename_options_jobquestion_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitergroup',
            name='job_question_insert_privilege',
            field=models.BooleanField(default=False),
        ),
    ]
