# Generated by Django 4.2.2 on 2023-06-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0021_remove_profile_company_name_profile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_answers', to='jobseekapp.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekapp.jobquestion')),
            ],
        ),
    ]
