# Generated by Django 4.2.2 on 2023-07-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0025_candidateprofile_resume_alter_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='jobseekapp.candidateprofile'),
        ),
    ]
