# Generated by Django 4.2.2 on 2023-07-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0026_remove_candidateprofile_resume_remove_resume_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
