# Generated by Django 4.2.2 on 2023-07-02 16:31

from django.db import migrations, models
import jobseekapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0031_auto_20230702_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=jobseekapp.models.resume_file_path),
        ),
    ]
