# Generated by Django 4.2.2 on 2023-07-02 16:50

from django.db import migrations
import os
from django.utils.text import slugify


def update_resume_save_method(apps, schema_editor):
    Resume = apps.get_model('jobseekapp', 'Resume')

    def new_save(self, *args, **kwargs):
        if not self.id:
            # New resume, generate a unique name
            name, extension = os.path.splitext(self.file.name)
            slug = slugify(name)
            counter = 1
            unique_name = slug
            while Resume.objects.filter(name=unique_name).exists():
                unique_name = f"{slug}-{counter}"
                counter += 1
            self.name = unique_name
        Resume._base_manager._update(self, *args, **kwargs)

    Resume.save = new_save


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0032_alter_resume_file'),
    ]

    operations = [
        migrations.RunPython(update_resume_save_method),
    ]
