# Generated by Django 4.2.2 on 2023-07-02 17:01

from django.db import migrations


def update_resume_file_names(apps, schema_editor):
    Resume = apps.get_model('jobseekapp', 'Resume')
    for resume in Resume.objects.all():
        file_name = resume.name
        counter = 1
        while Resume.objects.filter(file__icontains=file_name).exists():
            file_name = f"{resume.name}{counter}"
            counter += 1
        resume.file.name = f"resumes/{file_name}"
        resume.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0033_auto_20230702_1350'),
    ]

    operations = [
        migrations.RunPython(update_resume_file_names),
    ]
