# Generated by Django 4.2.2 on 2023-07-02 17:32

from django.db import migrations
import os


def update_resume_file_names(apps, schema_editor):
    Resume = apps.get_model('jobseekapp', 'Resume')
    for resume in Resume.objects.all():
        filename, file_extension = os.path.splitext(resume.file.name)
        base_filename = os.path.basename(filename)
        counter = 1
        unique_filename = base_filename
        while Resume.objects.filter(file__icontains=f"{unique_filename}{file_extension}").exists():
            unique_filename = f"{base_filename}{counter}"
            counter += 1
        new_filename = f"{unique_filename}{file_extension}"
        resume.file.name = os.path.join(os.path.dirname(resume.file.name), new_filename)
        resume.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0035_auto_20230702_1424'),
    ]

    operations = [
        migrations.RunPython(update_resume_file_names),
    ]
