# Generated by Django 4.2.2 on 2023-07-02 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekapp', '0039_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(on_delete=models.CASCADE, to='jobseekapp.Resume'),
        ),
    ]
